#!/usr/bin/env bun
import { $, file, write } from 'bun';
import { projectRoot } from '#test/helpers';

interface PkitsCaseRecord {
	readonly section: string;
	readonly testNumber: string;
	readonly title: string;
	readonly certs: readonly string[];
	readonly crls: readonly string[];
	readonly shouldValidate: boolean;
	readonly initialPolicySet?: readonly string[] | 'any';
	readonly requireExplicitPolicy?: boolean;
	readonly inhibitPolicyMapping?: boolean;
	readonly inhibitAnyPolicy?: boolean;
	readonly expectedUserConstrainedPolicies?: readonly string[];
}

interface ParsedPkitsCase {
	readonly pkitsCase: PkitsCaseRecord;
	readonly nextLineIndex: number;
}

interface MutablePkitsCaseRecord {
	certs: readonly string[];
	crls: readonly string[];
	emittedTestNumber: string;
	shouldValidate?: boolean;
	initialPolicySet?: readonly string[] | 'any';
	requireExplicitPolicy?: boolean;
	inhibitPolicyMapping?: boolean;
	inhibitAnyPolicy?: boolean;
	expectedUserConstrainedPolicies?: readonly string[];
}

const POLICY_NAME_TO_OID = {
	anyPolicy: '2.5.29.32.0',
	'NIST-test-policy-1': '2.16.840.1.101.3.2.1.48.1',
	'NIST-test-policy-2': '2.16.840.1.101.3.2.1.48.2',
	'NIST-test-policy-3': '2.16.840.1.101.3.2.1.48.3',
	'NIST-test-policy-4': '2.16.840.1.101.3.2.1.48.4',
	'NIST-test-policy-5': '2.16.840.1.101.3.2.1.48.5',
	'NIST-test-policy-6': '2.16.840.1.101.3.2.1.48.6',
} as const;

function mapPolicyName(policy: string): string {
	switch (policy) {
		case 'anyPolicy':
			return POLICY_NAME_TO_OID.anyPolicy;
		case 'NIST-test-policy-1':
			return POLICY_NAME_TO_OID['NIST-test-policy-1'];
		case 'NIST-test-policy-2':
			return POLICY_NAME_TO_OID['NIST-test-policy-2'];
		case 'NIST-test-policy-3':
			return POLICY_NAME_TO_OID['NIST-test-policy-3'];
		case 'NIST-test-policy-4':
			return POLICY_NAME_TO_OID['NIST-test-policy-4'];
		case 'NIST-test-policy-5':
			return POLICY_NAME_TO_OID['NIST-test-policy-5'];
		case 'NIST-test-policy-6':
			return POLICY_NAME_TO_OID['NIST-test-policy-6'];
		default:
			throw new Error(`Unknown PKITS policy token: ${policy}`);
	}
}

function parseQuotedNames(lines: readonly string[], startIndex: number): readonly string[] {
	const names: string[] = [];
	for (let lineIndex = startIndex; lineIndex < lines.length; lineIndex += 1) {
		const line = lines[lineIndex]?.trim();
		if (line === undefined) {
			break;
		}
		for (const match of line.matchAll(/"([^"]+)"/g)) {
			const name = match[1];
			if (name !== undefined) {
				names.push(name);
			}
		}
		if (line.endsWith('};')) {
			break;
		}
	}
	return names;
}

function mapPolicyNames(rawPolicies: string): readonly string[] | 'any' {
	const policies = rawPolicies
		.split(',')
		.map((policy) => policy.trim())
		.filter((policy) => policy.length > 0);
	const firstPolicy = policies[0];
	if (policies.length === 1 && firstPolicy === 'anyPolicy') {
		return 'any';
	}
	return policies.map((policy) => mapPolicyName(policy));
}

function formatCaseRecord(pkitsCase: PkitsCaseRecord): string {
	return JSON.stringify(pkitsCase, null, '\t')
		.replaceAll('"section"', 'section')
		.replaceAll('"testNumber"', 'testNumber')
		.replaceAll('"title"', 'title')
		.replaceAll('"certs"', 'certs')
		.replaceAll('"crls"', 'crls')
		.replaceAll('"shouldValidate"', 'shouldValidate')
		.replaceAll('"initialPolicySet"', 'initialPolicySet')
		.replaceAll('"requireExplicitPolicy"', 'requireExplicitPolicy')
		.replaceAll('"inhibitPolicyMapping"', 'inhibitPolicyMapping')
		.replaceAll('"inhibitAnyPolicy"', 'inhibitAnyPolicy')
		.replaceAll('"expectedUserConstrainedPolicies"', 'expectedUserConstrainedPolicies');
}

async function main(): Promise<void> {
	const upstreamPath = `${import.meta.dir}/upstream/pkits_testcases-inl.h`;
	const manifestPath = `${import.meta.dir}/manifest.ts`;
	const source = await file(upstreamPath).text();
	const lines = source.split(/\r?\n/u);
	const cases: PkitsCaseRecord[] = [];

	for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
		const parsedCase = parsePkitsCase(lines, lineIndex);
		if (parsedCase === undefined) continue;
		cases.push(parsedCase.pkitsCase);
		lineIndex = parsedCase.nextLineIndex;
	}

	const manifest = `\
// Auto-generated by test/fixtures/pkits/generate-manifest.ts.
// Do not edit by hand.

/** PKITS test case metadata extracted from pkits_testcases-inl.h. */
export interface PkitsCase {
	readonly section: string;
	readonly testNumber: string;
	readonly title: string;
	readonly certs: readonly string[];
	readonly crls: readonly string[];
	readonly shouldValidate: boolean;
	readonly initialPolicySet?: readonly string[] | 'any';
	readonly requireExplicitPolicy?: boolean;
	readonly inhibitPolicyMapping?: boolean;
	readonly inhibitAnyPolicy?: boolean;
	readonly expectedUserConstrainedPolicies?: readonly string[];
}

export const PKITS_CASES = [
	${cases.map((pkitsCase) => `\t${formatCaseRecord(pkitsCase)}`).join(',\n')}
] as const satisfies readonly PkitsCase[];
`;

	await write(manifestPath, manifest).then(() => {
		console.info(`Wrote manifest with ${cases.length} cases to ${manifestPath}`);
	});
	await $`bunx dprint fmt --log-level error ${manifestPath}`.cwd(projectRoot);
}

function parsePkitsCase(lines: readonly string[], lineIndex: number): ParsedPkitsCase | undefined {
	const commentLine = lines[lineIndex]?.trim();
	const commentMatch = commentLine?.match(
		/^\/\/ (?<testNumber>\d+\.\d+\.\d+(?:\.\d+)?) (?<title>.+?)(?: \(Subpart \d+\))?$/u,
	);
	if (commentMatch === null || commentMatch === undefined) return undefined;
	if (!lines[lineIndex + 1]?.includes('WRAPPED_TYPED_TEST_P(')) return undefined;
	const title = commentMatch.groups?.title;
	const emittedTestNumber = commentMatch.groups?.testNumber;
	if (title === undefined || emittedTestNumber === undefined) {
		throw new Error(`Malformed PKITS comment line: ${commentLine}`);
	}
	const record: MutablePkitsCaseRecord = {
		certs: [],
		crls: [],
		emittedTestNumber,
	};
	let cursor = lineIndex + 2;
	for (; cursor < lines.length; cursor += 1) {
		const line = lines[cursor]?.trim();
		if (line === undefined || line === 'this->RunTest(certs, crls, info);') break;
		applyPkitsCaseLine(lines, cursor, line, record);
	}
	if (record.shouldValidate === undefined) {
		throw new Error(`Missing should_validate for PKITS case ${record.emittedTestNumber}`);
	}
	return {
		pkitsCase: buildPkitsCaseRecord(title, record),
		nextLineIndex: cursor,
	};
}

function applyPkitsCaseLine(
	lines: readonly string[],
	lineIndex: number,
	line: string,
	record: MutablePkitsCaseRecord,
): void {
	if (line.startsWith('const char* const certs[] = {')) {
		record.certs = parseQuotedNames(lines, lineIndex);
		return;
	}
	if (line.startsWith('const char* const crls[] = {')) {
		record.crls = parseQuotedNames(lines, lineIndex);
		return;
	}
	if (line.startsWith('info.test_number = ')) {
		record.emittedTestNumber = line.match(/"([^"]+)"/u)?.[1] ?? record.emittedTestNumber;
		return;
	}
	if (line.startsWith('info.should_validate = ')) {
		record.shouldValidate = line.includes('true');
		return;
	}
	applyPkitsPolicyLine(line, record);
}

function applyPkitsPolicyLine(line: string, record: MutablePkitsCaseRecord): void {
	if (line.startsWith('info.SetInitialPolicySet(')) {
		record.initialPolicySet = mapPolicyNames(readQuotedPolicySet(line, 'policy set'));
	}
	if (line.startsWith('info.SetInitialExplicitPolicy(')) {
		record.requireExplicitPolicy = line.includes('true');
	}
	if (line.startsWith('info.SetInitialPolicyMappingInhibit(')) {
		record.inhibitPolicyMapping = line.includes('true');
	}
	if (line.startsWith('info.SetInitialInhibitAnyPolicy(')) {
		record.inhibitAnyPolicy = line.includes('true');
	}
	if (line.startsWith('info.SetUserConstrainedPolicySet(')) {
		const mappedPolicies = mapPolicyNames(readQuotedPolicySet(line, 'constrained policy set'));
		record.expectedUserConstrainedPolicies =
			mappedPolicies === 'any' ? ['2.5.29.32.0'] : mappedPolicies;
	}
}

function readQuotedPolicySet(line: string, label: string): string {
	const rawPolicies = line.match(/"([^"]*)"/u)?.[1];
	if (rawPolicies === undefined) {
		throw new Error(`Missing ${label} on line: ${line}`);
	}
	return rawPolicies;
}

function buildPkitsCaseRecord(title: string, record: MutablePkitsCaseRecord): PkitsCaseRecord {
	if (record.shouldValidate === undefined) {
		throw new Error(`Missing should_validate for PKITS case ${record.emittedTestNumber}`);
	}
	return {
		section: record.emittedTestNumber.split('.').slice(0, 2).join('.'),
		testNumber: record.emittedTestNumber,
		title,
		certs: record.certs,
		crls: record.crls,
		shouldValidate: record.shouldValidate,
		...(record.initialPolicySet === undefined ? {} : { initialPolicySet: record.initialPolicySet }),
		...(record.requireExplicitPolicy === undefined
			? {}
			: { requireExplicitPolicy: record.requireExplicitPolicy }),
		...(record.inhibitPolicyMapping === undefined
			? {}
			: { inhibitPolicyMapping: record.inhibitPolicyMapping }),
		...(record.inhibitAnyPolicy === undefined ? {} : { inhibitAnyPolicy: record.inhibitAnyPolicy }),
		...(record.expectedUserConstrainedPolicies === undefined
			? {}
			: { expectedUserConstrainedPolicies: record.expectedUserConstrainedPolicies }),
	};
}

if (import.meta.main) await main();
