import { describe, expect, it } from 'bun:test';
import {
	createCertificateSigningRequest,
	createSelfSignedCertificate,
	parseCertificateDer,
	parseCertificateSigningRequestDer,
} from '#micro509';
import { toHex } from '#micro509/internal/asn1/asn1.ts';
import { OIDS } from '#micro509/internal/asn1/oids.ts';
import {
	buildSubjectKeyIdentifierFromSubjectPublicKeyInfo,
	type ExtensionDefinition,
	getExtensionDefinition,
	listExtensionDefinitions,
	type MutableKnownParsedExtensionAccumulator,
} from '#micro509/internal/x509/extension-registry.ts';
import { exportSpkiDer, generateKeyPair } from '#micro509/keys/index.ts';

function applyDefinition<TParsed, TInput>(
	definition: ExtensionDefinition<TParsed, TInput>,
	input: TInput,
): MutableKnownParsedExtensionAccumulator {
	const encoded = definition.encode(input);
	const decoded = definition.decode(encoded);
	const accumulator: MutableKnownParsedExtensionAccumulator = {};
	definition.applyParsed(accumulator, decoded);
	return accumulator;
}

describe('extension registry', () => {
	it('lists the expected cert and CSR built-in definitions', () => {
		expect(listExtensionDefinitions().map((definition) => definition.oid)).toEqual([
			OIDS.basicConstraints,
			OIDS.keyUsage,
			OIDS.extendedKeyUsage,
			OIDS.subjectAltName,
			OIDS.nameConstraints,
			OIDS.certificatePolicies,
			OIDS.policyMappings,
			OIDS.policyConstraints,
			OIDS.inhibitAnyPolicy,
			OIDS.authorityInfoAccess,
			OIDS.cRLDistributionPoints,
			OIDS.subjectKeyIdentifier,
			OIDS.authorityKeyIdentifier,
		]);
		expect(listExtensionDefinitions('csr').map((definition) => definition.oid)).toEqual([
			OIDS.basicConstraints,
			OIDS.keyUsage,
			OIDS.extendedKeyUsage,
			OIDS.subjectAltName,
			OIDS.nameConstraints,
			OIDS.certificatePolicies,
			OIDS.policyMappings,
			OIDS.policyConstraints,
			OIDS.inhibitAnyPolicy,
			OIDS.authorityInfoAccess,
			OIDS.cRLDistributionPoints,
		]);
	});

	it('tracks default criticality and auto-generated metadata', () => {
		expect(getExtensionDefinition(OIDS.basicConstraints)).toMatchObject({
			defaultCritical: true,
			contexts: ['certificate', 'csr'],
		});
		expect(getExtensionDefinition(OIDS.subjectAltName)).toMatchObject({
			defaultCritical: false,
			contexts: ['certificate', 'csr'],
		});
		expect(getExtensionDefinition(OIDS.subjectKeyIdentifier)).toMatchObject({
			defaultCritical: false,
			autoGenerated: true,
			contexts: ['certificate'],
		});
		expect(getExtensionDefinition(OIDS.nameConstraints)).toMatchObject({
			defaultCritical: true,
			contexts: ['certificate', 'csr'],
		});
	});

	it('round-trips representative shared extension codecs', () => {
		expect(
			applyDefinition(getExtensionDefinition(OIDS.basicConstraints), {
				ca: true,
				pathLength: 1,
			}).basicConstraints,
		).toEqual({ ca: true, pathLength: 1 });

		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectAltName), [
				{ type: 'dns', value: 'example.test' },
				{ type: 'email', value: 'ops@example.test' },
				{ type: 'uri', value: 'https://example.test/app' },
			]).subjectAltNames,
		).toEqual([
			{ type: 'dns', value: 'example.test' },
			{ type: 'email', value: 'ops@example.test' },
			{ type: 'uri', value: 'https://example.test/app' },
		]);

		expect(
			applyDefinition(getExtensionDefinition(OIDS.certificatePolicies), [
				{
					policyIdentifier: '1.2.3.4.5',
					policyQualifiers: [{ type: 'cps', uri: 'https://example.test/cps' }],
				},
			]).certificatePolicies,
		).toEqual([
			{
				policyIdentifier: '1.2.3.4.5',
				policyQualifiers: [{ type: 'cps', uri: 'https://example.test/cps' }],
			},
		]);

		expect(
			applyDefinition(getExtensionDefinition(OIDS.authorityInfoAccess), [
				{ method: 'ocsp', uri: 'https://ocsp.example.test' },
				{ method: 'caIssuers', uri: 'https://example.test/issuer.pem' },
			]).authorityInfoAccess,
		).toEqual([
			{ method: 'ocsp', uri: 'https://ocsp.example.test' },
			{ method: 'caIssuers', uri: 'https://example.test/issuer.pem' },
		]);
	});

	it('round-trips certificate-only name constraints and key identifier codecs', () => {
		expect(
			applyDefinition(getExtensionDefinition(OIDS.nameConstraints), {
				permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
				excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
			}).nameConstraints,
		).toEqual({
			permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
			excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
		});

		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectKeyIdentifier), '01020304')
				.subjectKeyIdentifier,
		).toBe('01020304');
		expect(
			applyDefinition(getExtensionDefinition(OIDS.authorityKeyIdentifier), '0a0b0c0d')
				.authorityKeyIdentifier,
		).toBe('0a0b0c0d');
	});

	it('derives subject key identifiers from subjectPublicKeyInfo', async () => {
		const keyPair = await generateKeyPair();
		const subjectPublicKeyInfo = await exportSpkiDer(keyPair.publicKey);
		const subjectKeyIdentifier =
			buildSubjectKeyIdentifierFromSubjectPublicKeyInfo(subjectPublicKeyInfo);
		expect(subjectKeyIdentifier.length).toBe(20);
		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectKeyIdentifier), subjectKeyIdentifier)
				.subjectKeyIdentifier,
		).toBe(toHex(subjectKeyIdentifier));
	});

	it('round-trips registry-backed certificate extension building and parsing', async () => {
		const certificate = await createSelfSignedCertificate({
			subject: { commonName: 'registry-cert.example' },
			extensions: {
				basicConstraints: { ca: true, pathLength: 1 },
				keyUsage: ['keyCertSign', 'cRLSign'],
				extendedKeyUsage: ['serverAuth', { type: 'oid', value: '1.2.3.4.5.6' }],
				subjectAltNames: [
					{ type: 'dns', value: 'registry-cert.example' },
					{ type: 'uri', value: 'https://registry-cert.example' },
				],
				nameConstraints: {
					permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
					excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
				},
				certificatePolicies: [{ policyIdentifier: '1.2.3.4.5' }],
				policyMappings: [{ issuerDomainPolicy: '1.2.3.4.1', subjectDomainPolicy: '1.2.3.4.2' }],
				policyConstraints: { requireExplicitPolicy: 0, inhibitPolicyMapping: 1 },
				inhibitAnyPolicy: { skipCerts: 2 },
				authorityInfoAccess: [{ method: 'ocsp', uri: 'https://ocsp.example.test' }],
				crlDistributionPoints: [
					{
						distributionPoint: {
							fullName: [{ type: 'uri', value: 'https://example.test/root.crl' }],
						},
					},
				],
			},
		});

		const parsed = parseCertificateDer(certificate.certificate.der);
		expect(parsed.basicConstraints).toEqual({ ca: true, pathLength: 1 });
		expect(parsed.keyUsage).toEqual(['keyCertSign', 'cRLSign']);
		expect(parsed.extendedKeyUsage).toEqual(['serverAuth', { type: 'oid', value: '1.2.3.4.5.6' }]);
		expect(parsed.subjectAltNames).toEqual([
			{ type: 'dns', value: 'registry-cert.example' },
			{ type: 'uri', value: 'https://registry-cert.example' },
		]);
		expect(parsed.nameConstraints).toEqual({
			permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
			excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
		});
		expect(parsed.certificatePolicies).toEqual([{ policyIdentifier: '1.2.3.4.5' }]);
		expect(parsed.policyMappings).toEqual([
			{ issuerDomainPolicy: '1.2.3.4.1', subjectDomainPolicy: '1.2.3.4.2' },
		]);
		expect(parsed.policyConstraints).toEqual({ requireExplicitPolicy: 0, inhibitPolicyMapping: 1 });
		expect(parsed.inhibitAnyPolicy).toEqual({ skipCerts: 2 });
		expect(parsed.authorityInfoAccess).toEqual([
			{ method: 'ocsp', uri: 'https://ocsp.example.test' },
		]);
		expect(parsed.crlDistributionPoints).toEqual([
			{
				distributionPoint: {
					fullName: [{ type: 'uri', value: 'https://example.test/root.crl' }],
				},
			},
		]);
		expect(parsed.subjectKeyIdentifier).toBeDefined();
		expect(parsed.authorityKeyIdentifier).toBe(parsed.subjectKeyIdentifier);
	});

	it('round-trips registry-backed CSR requested extensions and parsing', async () => {
		const keyPair = await generateKeyPair();
		const csr = await createCertificateSigningRequest({
			subject: { commonName: 'registry-csr.example' },
			publicKey: keyPair.publicKey,
			signerPrivateKey: keyPair.privateKey,
			extensions: {
				basicConstraints: { ca: true, pathLength: 0 },
				keyUsage: ['keyCertSign', 'cRLSign'],
				extendedKeyUsage: ['clientAuth'],
				subjectAltNames: [{ type: 'dns', value: 'registry-csr.example' }],
				nameConstraints: {
					permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
					excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
				},
				certificatePolicies: [{ policyIdentifier: '1.2.3.7.8' }],
				policyMappings: [{ issuerDomainPolicy: '1.2.3.7.1', subjectDomainPolicy: '1.2.3.7.2' }],
				policyConstraints: { requireExplicitPolicy: 1 },
				inhibitAnyPolicy: { skipCerts: 3 },
				authorityInfoAccess: [{ method: 'ocsp', uri: 'https://csr-ocsp.example.test' }],
				crlDistributionPoints: [
					{
						distributionPoint: {
							fullName: [{ type: 'uri', value: 'https://example.test/csr.crl' }],
						},
					},
				],
			},
		});
		const parsed = parseCertificateSigningRequestDer(csr.der);
		expect(parsed.basicConstraints).toEqual({ ca: true, pathLength: 0 });
		expect(parsed.keyUsage).toEqual(['keyCertSign', 'cRLSign']);
		expect(parsed.extendedKeyUsage).toEqual(['clientAuth']);
		expect(parsed.subjectAltNames).toEqual([{ type: 'dns', value: 'registry-csr.example' }]);
		expect(parsed.nameConstraints).toEqual({
			permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
			excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
		});
		expect(parsed.certificatePolicies).toEqual([{ policyIdentifier: '1.2.3.7.8' }]);
		expect(parsed.policyMappings).toEqual([
			{ issuerDomainPolicy: '1.2.3.7.1', subjectDomainPolicy: '1.2.3.7.2' },
		]);
		expect(parsed.policyConstraints).toEqual({ requireExplicitPolicy: 1 });
		expect(parsed.inhibitAnyPolicy).toEqual({ skipCerts: 3 });
		expect(parsed.authorityInfoAccess).toEqual([
			{ method: 'ocsp', uri: 'https://csr-ocsp.example.test' },
		]);
		expect(parsed.crlDistributionPoints).toEqual([
			{
				distributionPoint: {
					fullName: [{ type: 'uri', value: 'https://example.test/csr.crl' }],
				},
			},
		]);
	});

	it('rejects certificate-only known extensions in CSR customExtensions', async () => {
		const keyPair = await generateKeyPair();
		expect(
			createCertificateSigningRequest({
				subject: { commonName: 'csr-custom-extension.example' },
				publicKey: keyPair.publicKey,
				signerPrivateKey: keyPair.privateKey,
				extensions: {
					customExtensions: [
						{ oid: OIDS.subjectKeyIdentifier, value: Uint8Array.of(0x04, 0x04, 1, 2, 3, 4) },
					],
				},
			}),
		).rejects.toThrow('not supported in csr context');
	});
});
