import { describe, expect, it } from 'bun:test';
import { createCertificateSigningRequest, parseCertificateSigningRequestDer } from '#micro509';
import { toHex } from '#micro509/asn1.ts';
import {
	buildSubjectKeyIdentifierFromSubjectPublicKeyInfo,
	type ExtensionDefinition,
	getExtensionDefinition,
	listExtensionDefinitions,
	type MutableKnownParsedExtensionAccumulator,
} from '#micro509/extension-registry.ts';
import { exportSpkiDer, generateKeyPair } from '#micro509/keys.ts';
import { OIDS } from '#micro509/oids.ts';

function applyDefinition<TParsed, TInput>(
	definition: ExtensionDefinition<TParsed, TInput>,
	input: TInput,
): MutableKnownParsedExtensionAccumulator {
	const encoded = definition.encode(input);
	const decoded = definition.decode(encoded);
	const accumulator: MutableKnownParsedExtensionAccumulator = {};
	definition.applyParsed(accumulator, decoded);
	return accumulator;
}

describe('extension registry', () => {
	it('lists the expected cert and CSR built-in definitions', () => {
		expect(listExtensionDefinitions().map((definition) => definition.oid)).toEqual([
			OIDS.basicConstraints,
			OIDS.keyUsage,
			OIDS.extendedKeyUsage,
			OIDS.subjectAltName,
			OIDS.nameConstraints,
			OIDS.certificatePolicies,
			OIDS.policyMappings,
			OIDS.policyConstraints,
			OIDS.inhibitAnyPolicy,
			OIDS.authorityInfoAccess,
			OIDS.cRLDistributionPoints,
			OIDS.subjectKeyIdentifier,
			OIDS.authorityKeyIdentifier,
		]);
		expect(listExtensionDefinitions('csr').map((definition) => definition.oid)).toEqual([
			OIDS.basicConstraints,
			OIDS.keyUsage,
			OIDS.extendedKeyUsage,
			OIDS.subjectAltName,
			OIDS.nameConstraints,
			OIDS.certificatePolicies,
			OIDS.policyMappings,
			OIDS.policyConstraints,
			OIDS.inhibitAnyPolicy,
			OIDS.authorityInfoAccess,
			OIDS.cRLDistributionPoints,
		]);
	});

	it('tracks default criticality and auto-generated metadata', () => {
		expect(getExtensionDefinition(OIDS.basicConstraints)).toMatchObject({
			defaultCritical: true,
			contexts: ['certificate', 'csr'],
		});
		expect(getExtensionDefinition(OIDS.subjectAltName)).toMatchObject({
			defaultCritical: false,
			contexts: ['certificate', 'csr'],
		});
		expect(getExtensionDefinition(OIDS.subjectKeyIdentifier)).toMatchObject({
			defaultCritical: false,
			autoGenerated: true,
			contexts: ['certificate'],
		});
		expect(getExtensionDefinition(OIDS.nameConstraints)).toMatchObject({
			defaultCritical: true,
			contexts: ['certificate', 'csr'],
		});
	});

	it('round-trips representative shared extension codecs', () => {
		expect(
			applyDefinition(getExtensionDefinition(OIDS.basicConstraints), {
				ca: true,
				pathLength: 1,
			}).basicConstraints,
		).toEqual({ ca: true, pathLength: 1 });

		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectAltName), [
				{ type: 'dns', value: 'example.test' },
				{ type: 'email', value: 'ops@example.test' },
				{ type: 'uri', value: 'https://example.test/app' },
			]).subjectAltNames,
		).toEqual([
			{ type: 'dns', value: 'example.test' },
			{ type: 'email', value: 'ops@example.test' },
			{ type: 'uri', value: 'https://example.test/app' },
		]);

		expect(
			applyDefinition(getExtensionDefinition(OIDS.certificatePolicies), [
				{
					policyIdentifier: '1.2.3.4.5',
					policyQualifiers: [{ type: 'cps', uri: 'https://example.test/cps' }],
				},
			]).certificatePolicies,
		).toEqual([
			{
				policyIdentifier: '1.2.3.4.5',
				policyQualifiers: [{ type: 'cps', uri: 'https://example.test/cps' }],
			},
		]);

		expect(
			applyDefinition(getExtensionDefinition(OIDS.authorityInfoAccess), [
				{ method: 'ocsp', uri: 'https://ocsp.example.test' },
				{ method: 'caIssuers', uri: 'https://example.test/issuer.pem' },
			]).authorityInfoAccess,
		).toEqual([
			{ method: 'ocsp', uri: 'https://ocsp.example.test' },
			{ method: 'caIssuers', uri: 'https://example.test/issuer.pem' },
		]);
	});

	it('round-trips certificate-only name constraints and key identifier codecs', () => {
		expect(
			applyDefinition(getExtensionDefinition(OIDS.nameConstraints), {
				permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
				excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
			}).nameConstraints,
		).toEqual({
			permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
			excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
		});

		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectKeyIdentifier), '01020304')
				.subjectKeyIdentifier,
		).toBe('01020304');
		expect(
			applyDefinition(getExtensionDefinition(OIDS.authorityKeyIdentifier), '0a0b0c0d')
				.authorityKeyIdentifier,
		).toBe('0a0b0c0d');
	});

	it('derives subject key identifiers from subjectPublicKeyInfo', async () => {
		const keyPair = await generateKeyPair();
		const subjectPublicKeyInfo = await exportSpkiDer(keyPair.publicKey);
		const subjectKeyIdentifier =
			buildSubjectKeyIdentifierFromSubjectPublicKeyInfo(subjectPublicKeyInfo);
		expect(subjectKeyIdentifier.length).toBe(20);
		expect(
			applyDefinition(getExtensionDefinition(OIDS.subjectKeyIdentifier), subjectKeyIdentifier)
				.subjectKeyIdentifier,
		).toBe(toHex(subjectKeyIdentifier));
	});

	it('round-trips name constraints through CSR creation and parsing', async () => {
		const keyPair = await generateKeyPair();
		const csr = await createCertificateSigningRequest({
			subject: { commonName: 'registry-csr.example' },
			publicKey: keyPair.publicKey,
			signerPrivateKey: keyPair.privateKey,
			extensions: {
				nameConstraints: {
					permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
					excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
				},
			},
		});
		expect(parseCertificateSigningRequestDer(csr.der).nameConstraints).toEqual({
			permittedSubtrees: [{ base: { type: 'dns', value: '.example.test' } }],
			excludedSubtrees: [{ base: { type: 'email', value: 'blocked@example.test' } }],
		});
	});
});
