#:schema ../actup-v2/schemas/actup-config.schema.json

update_policy    = "latest"
ref_style        = "sha"
branch_policy    = "update"
allow_prerelease = false
# ignore           = ["denoland/setup-deno@v2"]

[fetch]
api_mode          = "graphql"
max_tags_per_repo = 100
