[install]
linker = "hoisted"

[test]
coveragePathIgnorePatterns = ["test/**", "dist/**"]
coverageReporter           = ["text", "lcov"]
coverageSkipTestFiles      = true
reporter.junit             = "test-results.xml"

[run]
noOrphans = true
