[install]
linker = "hoisted"

[test]
concurrentTestGlob         = "**/*{differential,fuzz}*.test.ts"
coveragePathIgnorePatterns = ["test/**", "dist/**", "packages/**"]
coverageReporter           = ["text", "lcov"]
coverageSkipTestFiles      = true
coverageThreshold          = 0.80                                   # prevents bun from exiting non-zero
reporter.junit             = "test-results.xml"

[run]
noOrphans = true
