import { defineConfig } from 'tsdown';

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		certificate: 'src/certificate.ts',
		crl: 'src/crl.ts',
		csr: 'src/csr.ts',
		extensions: 'src/extensions.ts',
		identity: 'src/identity.ts',
		keys: 'src/keys/index.ts',
		name: 'src/name.ts',
		'name-constraints': 'src/name-constraints.ts',
		ocsp: 'src/ocsp.ts',
		parse: 'src/parse.ts',
		pem: 'src/pem/index.ts',
		pfx: 'src/pfx.ts',
		pkcs7: 'src/pkcs7.ts',
		'pkcs12-mac': 'src/pkcs12-mac.ts',
		policy: 'src/policy.ts',
		result: 'src/result/index.ts',
		revocation: 'src/revocation.ts',
		verify: 'src/verify/index.ts',
		x509: 'src/x509/index.ts',
	},
	name: 'micro509',
	format: ['esm'],
	dts: true,
	clean: true,
	platform: 'neutral',
	target: 'es2024',
	tsconfig: 'tsconfig.src.json',
	sourcemap: true,
	unbundle: true,
	hash: false,
	minify: true,
	inputOptions: {
		resolve: {
			mainFields: ['browser', 'module', 'main'],
		},
	},
	exports: true,
	onSuccess: 'bunx sort-package-json --quiet package.json',
	attw: { profile: 'esm-only', ignoreRules: ['no-resolution'] },
	unused: true,
	publint: true,
});
