import { defineConfig } from 'tsdown';

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		certificate: 'src/certificate.ts',
		crl: 'src/crl.ts',
		csr: 'src/csr.ts',
		extensions: 'src/extensions.ts',
		identity: 'src/identity.ts',
		keys: 'src/keys.ts',
		name: 'src/name.ts',
		ocsp: 'src/ocsp.ts',
		parse: 'src/parse.ts',
		pem: 'src/pem.ts',
		pfx: 'src/pfx.ts',
		pkcs7: 'src/pkcs7.ts',
		'pkcs12-mac': 'src/pkcs12-mac.ts',
		revocation: 'src/revocation.ts',
		validation: 'src/validation.ts',
		verify: 'src/verify.ts',
	},
	format: ['esm'],
	dts: { oxc: true },
	clean: true,
	platform: 'neutral',
	target: 'es2023',
	tsconfig: 'tsconfig.src.json',
	sourcemap: false,
	unbundle: true,
	inputOptions: {
		resolve: {
			mainFields: ['browser', 'module', 'main'],
		},
	},
	exports: true,
	onSuccess: 'bunx sort-package-json --quiet package.json',
	attw: { profile: 'esm-only', ignoreRules: ['no-resolution'] },
	unused: true,
	publint: true,
});
