/**
 * Internal extension registry used by certificate and CSR parsing.
 *
 * This module maps supported extension OIDs to decode hooks that populate typed parse
 * results.
 */

import { hexToBytes, toHex } from './asn1.ts';
import {
	DEFAULT_MAX_DER_DEPTH,
	implicitPrimitiveContext,
	octetString,
	readRootElement,
	sequence,
} from './der.ts';
import type {
	AuthorityInformationAccess,
	BasicConstraints,
	CertificatePolicies,
	DistributionPoint,
	ExtendedKeyUsage,
	InhibitAnyPolicy,
	KeyUsage,
	NameConstraints,
	ParsedNameConstraintForm,
	PolicyConstraints,
	PolicyMappings,
	SubjectAltName,
} from './extensions.ts';
import {
	buildSubjectKeyIdentifier,
	encodeAuthorityInfoAccess,
	encodeBasicConstraints,
	encodeCertificatePolicies,
	encodeCrlDistributionPoints,
	encodeExtendedKeyUsage,
	encodeInhibitAnyPolicy,
	encodeKeyUsage,
	encodeNameConstraints,
	encodePolicyConstraints,
	encodePolicyMappings,
	encodeSubjectAltName,
} from './extensions.ts';
import { OIDS } from './oids.ts';
import type { ParsedDistributionPoint } from './parse.ts';
import {
	parseAuthorityInfoAccess,
	parseAuthorityKeyIdentifier,
	parseBasicConstraints,
	parseCertificatePolicies,
	parseCrlDistributionPoints,
	parseExtendedKeyUsage,
	parseInhibitAnyPolicy,
	parseKeyUsage,
	parseNameConstraints,
	parsePolicyConstraints,
	parsePolicyMappings,
	parseSubjectAltNames,
} from './parse.ts';

/**
 * Defines extension registry context.
 */
export type ExtensionRegistryContext = 'certificate' | 'csr';

/**
 * Describes known parsed extension accumulator.
 */
export interface KnownParsedExtensionAccumulator {
	/**
	 * Carries the basic constraints value.
	 */
	readonly basicConstraints?: BasicConstraints;
	/**
	 * Carries the key usage value.
	 */
	readonly keyUsage?: readonly KeyUsage[];
	/**
	 * Carries the extended key usage value.
	 */
	readonly extendedKeyUsage?: readonly ExtendedKeyUsage[];
	/**
	 * Carries the subject alt names value.
	 */
	readonly subjectAltNames?: readonly SubjectAltName[];
	/**
	 * Carries the nam e constraints value.
	 */
	readonly nameConstraints?: NameConstraints<ParsedNameConstraintForm>;
	/**
	 * Carries the certificate policies value.
	 */
	readonly certificatePolicies?: CertificatePolicies;
	/**
	 * Carries the policy mappings value.
	 */
	readonly policyMappings?: PolicyMappings;
	/**
	 * Carries the policy constraints value.
	 */
	readonly policyConstraints?: PolicyConstraints;
	/**
	 * Carries the inhibit any policy value.
	 */
	readonly inhibitAnyPolicy?: InhibitAnyPolicy;
	/**
	 * Carries the authority info access value.
	 */
	readonly authorityInfoAccess?: readonly AuthorityInformationAccess[];
	/**
	 * Carries the crl distribution points value.
	 */
	readonly crlDistributionPoints?: readonly ParsedDistributionPoint[];
	/**
	 * Carries the subject key identifier value.
	 */
	readonly subjectKeyIdentifier?: string;
	/**
	 * Carries the authority key identifier value.
	 */
	readonly authorityKeyIdentifier?: string;
}

/**
 * Describes mutable known parsed extension accumulator.
 */
export interface MutableKnownParsedExtensionAccumulator extends KnownParsedExtensionAccumulator {
	/**
	 * Carries the basic constraints value.
	 */
	basicConstraints?: BasicConstraints;
	/**
	 * Carries the key usage value.
	 */
	keyUsage?: readonly KeyUsage[];
	/**
	 * Carries the extended key usage value.
	 */
	extendedKeyUsage?: readonly ExtendedKeyUsage[];
	/**
	 * Carries the subject alt names value.
	 */
	subjectAltNames?: readonly SubjectAltName[];
	/**
	 * Carries the nam e constraints value.
	 */
	nameConstraints?: NameConstraints<ParsedNameConstraintForm>;
	/**
	 * Carries the certificate policies value.
	 */
	certificatePolicies?: CertificatePolicies;
	/**
	 * Carries the policy mappings value.
	 */
	policyMappings?: PolicyMappings;
	/**
	 * Carries the policy constraints value.
	 */
	policyConstraints?: PolicyConstraints;
	/**
	 * Carries the inhibit any policy value.
	 */
	inhibitAnyPolicy?: InhibitAnyPolicy;
	/**
	 * Carries the authority info access value.
	 */
	authorityInfoAccess?: readonly AuthorityInformationAccess[];
	/**
	 * Carries the crl distribution points value.
	 */
	crlDistributionPoints?: readonly ParsedDistributionPoint[];
	/**
	 * Carries the subject key identifier value.
	 */
	subjectKeyIdentifier?: string;
	/**
	 * Carries the authority key identifier value.
	 */
	authorityKeyIdentifier?: string;
}

/**
 * Describes the registry definition used for extension handling.
 */
export interface ExtensionDefinition<TParsed, TInput = TParsed> {
	/**
	 * Carries the oid value.
	 */
	readonly oid: string;
	/**
	 * Carries the contexts value.
	 */
	readonly contexts: readonly ExtensionRegistryContext[];
	/**
	 * Indicates whether default critical.
	 */
	readonly defaultCritical: boolean;
	/**
	 * Indicates whether auto generated.
	 */
	readonly autoGenerated?: boolean;
	/**
	 * decode.
	 *
	 * @param valueDer The value DER value.
	 * @returns The computed value.
	 */
	decode(valueDer: Uint8Array): TParsed;
	/**
	 * encode.
	 *
	 * @param value The value to process.
	 * @returns The computed value.
	 */
	encode(value: TInput): Uint8Array;
	/**
	 * apply parsed.
	 *
	 * @param accumulator The accumulator value.
	 * @param value The value to process.
	 */
	applyParsed(accumulator: MutableKnownParsedExtensionAccumulator, value: TParsed): void;
}

/**
 * Defines the basic constraints extension definition used by this module.
 */
export const BASIC_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<BasicConstraints> =
	defineExtensionDefinition<BasicConstraints>({
		oid: OIDS.basicConstraints,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseBasicConstraints(valueDer),
		encode: (value) => encodeBasicConstraints(value),
		applyParsed: (accumulator, value) => {
			accumulator.basicConstraints = value;
		},
	});

/**
 * Defines the key usage extension definition used by this module.
 */
export const KEY_USAGE_EXTENSION_DEFINITION: ExtensionDefinition<readonly KeyUsage[]> =
	defineExtensionDefinition<readonly KeyUsage[]>({
		oid: OIDS.keyUsage,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseKeyUsage(valueDer),
		encode: (value) => encodeKeyUsage(value),
		applyParsed: (accumulator, value) => {
			accumulator.keyUsage = value;
		},
	});

/**
 * Defines the extended key usage extension definition used by this module.
 */
export const EXTENDED_KEY_USAGE_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly ExtendedKeyUsage[]
> = defineExtensionDefinition<readonly ExtendedKeyUsage[]>({
	oid: OIDS.extendedKeyUsage,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseExtendedKeyUsage(valueDer),
	encode: (value) => encodeExtendedKeyUsage(value),
	applyParsed: (accumulator, value) => {
		accumulator.extendedKeyUsage = value;
	},
});

/**
 * Defines the subject alt name extension definition used by this module.
 */
export const SUBJECT_ALT_NAME_EXTENSION_DEFINITION: ExtensionDefinition<readonly SubjectAltName[]> =
	defineExtensionDefinition<readonly SubjectAltName[]>({
		oid: OIDS.subjectAltName,
		contexts: ['certificate', 'csr'],
		defaultCritical: false,
		decode: (valueDer) => parseSubjectAltNames(valueDer),
		encode: (value) => sequence(value.map(encodeSubjectAltName)),
		applyParsed: (accumulator, value) => {
			accumulator.subjectAltNames = value;
		},
	});

/**
 * Defines the name constraints extension definition used by this module.
 */
export const NAME_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<
	NameConstraints<ParsedNameConstraintForm>,
	NameConstraints
> = defineExtensionDefinition<NameConstraints<ParsedNameConstraintForm>, NameConstraints>({
	oid: OIDS.nameConstraints,
	contexts: ['certificate', 'csr'],
	defaultCritical: true,
	decode: (valueDer) => parseNameConstraints(valueDer),
	encode: (value) => encodeNameConstraints(value),
	applyParsed: (accumulator, value) => {
		accumulator.nameConstraints = value;
	},
});

/**
 * Defines the certificate policies extension definition used by this module.
 */
export const CERTIFICATE_POLICIES_EXTENSION_DEFINITION: ExtensionDefinition<CertificatePolicies> =
	defineExtensionDefinition<CertificatePolicies>({
		oid: OIDS.certificatePolicies,
		contexts: ['certificate', 'csr'],
		defaultCritical: false,
		decode: (valueDer) => parseCertificatePolicies(valueDer),
		encode: (value) => encodeCertificatePolicies(value),
		applyParsed: (accumulator, value) => {
			accumulator.certificatePolicies = value;
		},
	});

/**
 * Defines the policy mappings extension definition used by this module.
 */
export const POLICY_MAPPINGS_EXTENSION_DEFINITION: ExtensionDefinition<PolicyMappings> =
	defineExtensionDefinition<PolicyMappings>({
		oid: OIDS.policyMappings,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parsePolicyMappings(valueDer),
		encode: (value) => encodePolicyMappings(value),
		applyParsed: (accumulator, value) => {
			accumulator.policyMappings = value;
		},
	});

/**
 * Defines the policy constraints extension definition used by this module.
 */
export const POLICY_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<PolicyConstraints> =
	defineExtensionDefinition<PolicyConstraints>({
		oid: OIDS.policyConstraints,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parsePolicyConstraints(valueDer),
		encode: (value) => encodePolicyConstraints(value),
		applyParsed: (accumulator, value) => {
			accumulator.policyConstraints = value;
		},
	});

/**
 * Defines the inhibit any policy extension definition used by this module.
 */
export const INHIBIT_ANY_POLICY_EXTENSION_DEFINITION: ExtensionDefinition<InhibitAnyPolicy> =
	defineExtensionDefinition<InhibitAnyPolicy>({
		oid: OIDS.inhibitAnyPolicy,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseInhibitAnyPolicy(valueDer),
		encode: (value) => encodeInhibitAnyPolicy(value),
		applyParsed: (accumulator, value) => {
			accumulator.inhibitAnyPolicy = value;
		},
	});

/**
 * Defines the authority info access extension definition used by this module.
 */
export const AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly AuthorityInformationAccess[]
> = defineExtensionDefinition<readonly AuthorityInformationAccess[]>({
	oid: OIDS.authorityInfoAccess,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseAuthorityInfoAccess(valueDer),
	encode: (value) => encodeAuthorityInfoAccess(value),
	applyParsed: (accumulator, value) => {
		accumulator.authorityInfoAccess = value;
	},
});

/**
 * Defines the crl distribution points extension definition used by this module.
 */
export const CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly ParsedDistributionPoint[],
	readonly DistributionPoint[]
> = defineExtensionDefinition<readonly ParsedDistributionPoint[], readonly DistributionPoint[]>({
	oid: OIDS.cRLDistributionPoints,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseCrlDistributionPoints(valueDer),
	encode: (value) => encodeCrlDistributionPoints(value),
	applyParsed: (accumulator, value) => {
		accumulator.crlDistributionPoints = value;
	},
});

/**
 * Defines the subject key identifier extension definition used by this module.
 */
export const SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION: ExtensionDefinition<
	string,
	string | Uint8Array
> = defineExtensionDefinition<string, string | Uint8Array>({
	oid: OIDS.subjectKeyIdentifier,
	contexts: ['certificate'],
	defaultCritical: false,
	autoGenerated: true,
	decode: (valueDer) => decodeSubjectKeyIdentifier(valueDer),
	encode: (value) => octetString(normalizeKeyIdentifier(value)),
	applyParsed: (accumulator, value) => {
		accumulator.subjectKeyIdentifier = value;
	},
});

/**
 * Defines the authority key identifier extension definition used by this module.
 */
export const AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION: ExtensionDefinition<
	string | undefined,
	string | Uint8Array
> = defineExtensionDefinition<string | undefined, string | Uint8Array>({
	oid: OIDS.authorityKeyIdentifier,
	contexts: ['certificate'],
	defaultCritical: false,
	autoGenerated: true,
	decode: (valueDer) => parseAuthorityKeyIdentifier(valueDer),
	encode: (value) => sequence([implicitPrimitiveContext(0, normalizeKeyIdentifier(value))]),
	applyParsed: (accumulator, value) => {
		if (value !== undefined) {
			accumulator.authorityKeyIdentifier = value;
		}
	},
});

/**
 * Describes the registry definition used for known extension handling.
 */
export type KnownExtensionDefinition =
	| typeof BASIC_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof KEY_USAGE_EXTENSION_DEFINITION
	| typeof EXTENDED_KEY_USAGE_EXTENSION_DEFINITION
	| typeof SUBJECT_ALT_NAME_EXTENSION_DEFINITION
	| typeof NAME_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof CERTIFICATE_POLICIES_EXTENSION_DEFINITION
	| typeof POLICY_MAPPINGS_EXTENSION_DEFINITION
	| typeof POLICY_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof INHIBIT_ANY_POLICY_EXTENSION_DEFINITION
	| typeof AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION
	| typeof CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION
	| typeof SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION
	| typeof AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION;

/**
 * Defines the cert csr extension definitions used by this module.
 */
export const CERT_CSR_EXTENSION_DEFINITIONS: readonly KnownExtensionDefinition[] = [
	BASIC_CONSTRAINTS_EXTENSION_DEFINITION,
	KEY_USAGE_EXTENSION_DEFINITION,
	EXTENDED_KEY_USAGE_EXTENSION_DEFINITION,
	SUBJECT_ALT_NAME_EXTENSION_DEFINITION,
	NAME_CONSTRAINTS_EXTENSION_DEFINITION,
	CERTIFICATE_POLICIES_EXTENSION_DEFINITION,
	POLICY_MAPPINGS_EXTENSION_DEFINITION,
	POLICY_CONSTRAINTS_EXTENSION_DEFINITION,
	INHIBIT_ANY_POLICY_EXTENSION_DEFINITION,
	AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION,
	CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION,
	SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION,
	AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION,
];

/**
 * Defines the extension definition map used by this module.
 */
const EXTENSION_DEFINITION_MAP = new Map<string, KnownExtensionDefinition>(
	CERT_CSR_EXTENSION_DEFINITIONS.map((definition) => [definition.oid, definition]),
);

/**
 * Defines the parsed extension appliers used by this module.
 */
const PARSED_EXTENSION_APPLIERS = new Map<
	string,
	(accumulator: MutableKnownParsedExtensionAccumulator, valueDer: Uint8Array) => void
>([
	[
		BASIC_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(BASIC_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		KEY_USAGE_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(KEY_USAGE_EXTENSION_DEFINITION),
	],
	[
		EXTENDED_KEY_USAGE_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(EXTENDED_KEY_USAGE_EXTENSION_DEFINITION),
	],
	[
		SUBJECT_ALT_NAME_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(SUBJECT_ALT_NAME_EXTENSION_DEFINITION),
	],
	[
		NAME_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(NAME_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		CERTIFICATE_POLICIES_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(CERTIFICATE_POLICIES_EXTENSION_DEFINITION),
	],
	[
		POLICY_MAPPINGS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(POLICY_MAPPINGS_EXTENSION_DEFINITION),
	],
	[
		POLICY_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(POLICY_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		INHIBIT_ANY_POLICY_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(INHIBIT_ANY_POLICY_EXTENSION_DEFINITION),
	],
	[
		AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION),
	],
	[
		CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION),
	],
	[
		SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION),
	],
	[
		AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION),
	],
]);

/**
 * List extension definitions.
 *
 * @param context The registry context value.
 * @returns The computed value.
 */
export function listExtensionDefinitions(
	context?: ExtensionRegistryContext,
): readonly KnownExtensionDefinition[] {
	if (context === undefined) {
		return CERT_CSR_EXTENSION_DEFINITIONS;
	}
	return CERT_CSR_EXTENSION_DEFINITIONS.filter((definition) =>
		definition.contexts.includes(context),
	);
}

/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.basicConstraints,
): typeof BASIC_CONSTRAINTS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.keyUsage,
): typeof KEY_USAGE_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.extendedKeyUsage,
): typeof EXTENDED_KEY_USAGE_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.subjectAltName,
): typeof SUBJECT_ALT_NAME_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.nameConstraints,
): typeof NAME_CONSTRAINTS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.certificatePolicies,
): typeof CERTIFICATE_POLICIES_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.policyMappings,
): typeof POLICY_MAPPINGS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.policyConstraints,
): typeof POLICY_CONSTRAINTS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.inhibitAnyPolicy,
): typeof INHIBIT_ANY_POLICY_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.authorityInfoAccess,
): typeof AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.cRLDistributionPoints,
): typeof CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.subjectKeyIdentifier,
): typeof SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(
	oid: typeof OIDS.authorityKeyIdentifier,
): typeof AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(oid: string): KnownExtensionDefinition | undefined;
/**
 * Returns extension definition.
 *
 * @param oid The object identifier.
 * @returns The extension definition.
 */
export function getExtensionDefinition(oid: string): KnownExtensionDefinition | undefined {
	return EXTENSION_DEFINITION_MAP.get(oid);
}

/**
 * Decodes and apply known extension.
 *
 * @param context The registry context value.
 * @param oid The object identifier.
 * @param accumulator The accumulator value.
 * @param valueDer The value DER value.
 * @returns The decoded and apply known extension.
 */
export function decodeAndApplyKnownExtension(
	context: ExtensionRegistryContext,
	oid: string,
	accumulator: MutableKnownParsedExtensionAccumulator,
	valueDer: Uint8Array,
): boolean {
	const definition = getExtensionDefinition(oid);
	if (definition === undefined || !definition.contexts.includes(context)) {
		return false;
	}
	const applyParsed = PARSED_EXTENSION_APPLIERS.get(oid);
	if (applyParsed === undefined) {
		return false;
	}
	applyParsed(accumulator, valueDer);
	return true;
}

/**
 * Builds subject key identifier from subject public key info.
 *
 * @param subjectPublicKeyInfo The subject public key info value.
 * @returns The built subject key identifier from subject public key info.
 */
export function buildSubjectKeyIdentifierFromSubjectPublicKeyInfo(
	subjectPublicKeyInfo: Uint8Array,
): Uint8Array {
	return buildSubjectKeyIdentifier(subjectPublicKeyInfo);
}

/**
 * Define extension definition.
 *
 * @param definition The definition value.
 * @returns The computed value.
 */
function defineExtensionDefinition<TParsed, TInput = TParsed>(
	definition: ExtensionDefinition<TParsed, TInput>,
): ExtensionDefinition<TParsed, TInput> {
	return definition;
}

/**
 * Creates parsed extension applicator.
 *
 * @param definition The definition value.
 * @returns The created parsed extension applicator.
 */
function createParsedExtensionApplicator<TParsed, TInput>(
	definition: ExtensionDefinition<TParsed, TInput>,
): (accumulator: MutableKnownParsedExtensionAccumulator, valueDer: Uint8Array) => void {
	return (accumulator, valueDer) => {
		definition.applyParsed(accumulator, definition.decode(valueDer));
	};
}

/**
 * Normalizes key identifier.
 *
 * @param value The value to process.
 * @returns The computed value.
 */
function normalizeKeyIdentifier(value: string | Uint8Array): Uint8Array {
	return typeof value === 'string' ? hexToBytes(value) : new Uint8Array(value);
}

/**
 * Decodes subject key identifier.
 *
 * @param valueDer The value DER value.
 * @returns The decoded subject key identifier.
 */
function decodeSubjectKeyIdentifier(valueDer: Uint8Array): string {
	return toHex(readRootElement(valueDer, { maxDepth: DEFAULT_MAX_DER_DEPTH }).value);
}
