import { hexToBytes, toHex } from './asn1.ts';
import {
	DEFAULT_MAX_DER_DEPTH,
	implicitPrimitiveContext,
	octetString,
	readRootElement,
	sequence,
} from './der.ts';
import type {
	AuthorityInformationAccess,
	BasicConstraints,
	CertificatePolicies,
	DistributionPoint,
	ExtendedKeyUsage,
	InhibitAnyPolicy,
	KeyUsage,
	NameConstraints,
	ParsedNameConstraintForm,
	PolicyConstraints,
	PolicyMappings,
	SubjectAltName,
} from './extensions.ts';
import {
	buildSubjectKeyIdentifier,
	encodeAuthorityInfoAccess,
	encodeBasicConstraints,
	encodeCertificatePolicies,
	encodeCrlDistributionPoints,
	encodeExtendedKeyUsage,
	encodeInhibitAnyPolicy,
	encodeKeyUsage,
	encodeNameConstraints,
	encodePolicyConstraints,
	encodePolicyMappings,
	encodeSubjectAltName,
} from './extensions.ts';
import { OIDS } from './oids.ts';
import type { ParsedDistributionPoint } from './parse.ts';
import {
	parseAuthorityInfoAccess,
	parseAuthorityKeyIdentifier,
	parseBasicConstraints,
	parseCertificatePolicies,
	parseCrlDistributionPoints,
	parseExtendedKeyUsage,
	parseInhibitAnyPolicy,
	parseKeyUsage,
	parseNameConstraints,
	parsePolicyConstraints,
	parsePolicyMappings,
	parseSubjectAltNames,
} from './parse.ts';

export type ExtensionRegistryContext = 'certificate' | 'csr';

export interface KnownParsedExtensionAccumulator {
	readonly basicConstraints?: BasicConstraints;
	readonly keyUsage?: readonly KeyUsage[];
	readonly extendedKeyUsage?: readonly ExtendedKeyUsage[];
	readonly subjectAltNames?: readonly SubjectAltName[];
	readonly nameConstraints?: NameConstraints<ParsedNameConstraintForm>;
	readonly certificatePolicies?: CertificatePolicies;
	readonly policyMappings?: PolicyMappings;
	readonly policyConstraints?: PolicyConstraints;
	readonly inhibitAnyPolicy?: InhibitAnyPolicy;
	readonly authorityInfoAccess?: readonly AuthorityInformationAccess[];
	readonly crlDistributionPoints?: readonly ParsedDistributionPoint[];
	readonly subjectKeyIdentifier?: string;
	readonly authorityKeyIdentifier?: string;
}

export interface MutableKnownParsedExtensionAccumulator extends KnownParsedExtensionAccumulator {
	basicConstraints?: BasicConstraints;
	keyUsage?: readonly KeyUsage[];
	extendedKeyUsage?: readonly ExtendedKeyUsage[];
	subjectAltNames?: readonly SubjectAltName[];
	nameConstraints?: NameConstraints<ParsedNameConstraintForm>;
	certificatePolicies?: CertificatePolicies;
	policyMappings?: PolicyMappings;
	policyConstraints?: PolicyConstraints;
	inhibitAnyPolicy?: InhibitAnyPolicy;
	authorityInfoAccess?: readonly AuthorityInformationAccess[];
	crlDistributionPoints?: readonly ParsedDistributionPoint[];
	subjectKeyIdentifier?: string;
	authorityKeyIdentifier?: string;
}

export interface ExtensionDefinition<TParsed, TInput = TParsed> {
	readonly oid: string;
	readonly contexts: readonly ExtensionRegistryContext[];
	readonly defaultCritical: boolean;
	readonly autoGenerated?: boolean;
	decode(valueDer: Uint8Array): TParsed;
	encode(value: TInput): Uint8Array;
	applyParsed(accumulator: MutableKnownParsedExtensionAccumulator, value: TParsed): void;
}

export const BASIC_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<BasicConstraints> =
	defineExtensionDefinition<BasicConstraints>({
		oid: OIDS.basicConstraints,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseBasicConstraints(valueDer),
		encode: (value) => encodeBasicConstraints(value),
		applyParsed: (accumulator, value) => {
			accumulator.basicConstraints = value;
		},
	});

export const KEY_USAGE_EXTENSION_DEFINITION: ExtensionDefinition<readonly KeyUsage[]> =
	defineExtensionDefinition<readonly KeyUsage[]>({
		oid: OIDS.keyUsage,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseKeyUsage(valueDer),
		encode: (value) => encodeKeyUsage(value),
		applyParsed: (accumulator, value) => {
			accumulator.keyUsage = value;
		},
	});

export const EXTENDED_KEY_USAGE_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly ExtendedKeyUsage[]
> = defineExtensionDefinition<readonly ExtendedKeyUsage[]>({
	oid: OIDS.extendedKeyUsage,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseExtendedKeyUsage(valueDer),
	encode: (value) => encodeExtendedKeyUsage(value),
	applyParsed: (accumulator, value) => {
		accumulator.extendedKeyUsage = value;
	},
});

export const SUBJECT_ALT_NAME_EXTENSION_DEFINITION: ExtensionDefinition<readonly SubjectAltName[]> =
	defineExtensionDefinition<readonly SubjectAltName[]>({
		oid: OIDS.subjectAltName,
		contexts: ['certificate', 'csr'],
		defaultCritical: false,
		decode: (valueDer) => parseSubjectAltNames(valueDer),
		encode: (value) => sequence(value.map(encodeSubjectAltName)),
		applyParsed: (accumulator, value) => {
			accumulator.subjectAltNames = value;
		},
	});

export const NAME_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<
	NameConstraints<ParsedNameConstraintForm>,
	NameConstraints
> = defineExtensionDefinition<NameConstraints<ParsedNameConstraintForm>, NameConstraints>({
	oid: OIDS.nameConstraints,
	contexts: ['certificate', 'csr'],
	defaultCritical: true,
	decode: (valueDer) => parseNameConstraints(valueDer),
	encode: (value) => encodeNameConstraints(value),
	applyParsed: (accumulator, value) => {
		accumulator.nameConstraints = value;
	},
});

export const CERTIFICATE_POLICIES_EXTENSION_DEFINITION: ExtensionDefinition<CertificatePolicies> =
	defineExtensionDefinition<CertificatePolicies>({
		oid: OIDS.certificatePolicies,
		contexts: ['certificate', 'csr'],
		defaultCritical: false,
		decode: (valueDer) => parseCertificatePolicies(valueDer),
		encode: (value) => encodeCertificatePolicies(value),
		applyParsed: (accumulator, value) => {
			accumulator.certificatePolicies = value;
		},
	});

export const POLICY_MAPPINGS_EXTENSION_DEFINITION: ExtensionDefinition<PolicyMappings> =
	defineExtensionDefinition<PolicyMappings>({
		oid: OIDS.policyMappings,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parsePolicyMappings(valueDer),
		encode: (value) => encodePolicyMappings(value),
		applyParsed: (accumulator, value) => {
			accumulator.policyMappings = value;
		},
	});

export const POLICY_CONSTRAINTS_EXTENSION_DEFINITION: ExtensionDefinition<PolicyConstraints> =
	defineExtensionDefinition<PolicyConstraints>({
		oid: OIDS.policyConstraints,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parsePolicyConstraints(valueDer),
		encode: (value) => encodePolicyConstraints(value),
		applyParsed: (accumulator, value) => {
			accumulator.policyConstraints = value;
		},
	});

export const INHIBIT_ANY_POLICY_EXTENSION_DEFINITION: ExtensionDefinition<InhibitAnyPolicy> =
	defineExtensionDefinition<InhibitAnyPolicy>({
		oid: OIDS.inhibitAnyPolicy,
		contexts: ['certificate', 'csr'],
		defaultCritical: true,
		decode: (valueDer) => parseInhibitAnyPolicy(valueDer),
		encode: (value) => encodeInhibitAnyPolicy(value),
		applyParsed: (accumulator, value) => {
			accumulator.inhibitAnyPolicy = value;
		},
	});

export const AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly AuthorityInformationAccess[]
> = defineExtensionDefinition<readonly AuthorityInformationAccess[]>({
	oid: OIDS.authorityInfoAccess,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseAuthorityInfoAccess(valueDer),
	encode: (value) => encodeAuthorityInfoAccess(value),
	applyParsed: (accumulator, value) => {
		accumulator.authorityInfoAccess = value;
	},
});

export const CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION: ExtensionDefinition<
	readonly ParsedDistributionPoint[],
	readonly DistributionPoint[]
> = defineExtensionDefinition<readonly ParsedDistributionPoint[], readonly DistributionPoint[]>({
	oid: OIDS.cRLDistributionPoints,
	contexts: ['certificate', 'csr'],
	defaultCritical: false,
	decode: (valueDer) => parseCrlDistributionPoints(valueDer),
	encode: (value) => encodeCrlDistributionPoints(value),
	applyParsed: (accumulator, value) => {
		accumulator.crlDistributionPoints = value;
	},
});

export const SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION: ExtensionDefinition<
	string,
	string | Uint8Array
> = defineExtensionDefinition<string, string | Uint8Array>({
	oid: OIDS.subjectKeyIdentifier,
	contexts: ['certificate'],
	defaultCritical: false,
	autoGenerated: true,
	decode: (valueDer) => decodeSubjectKeyIdentifier(valueDer),
	encode: (value) => octetString(normalizeKeyIdentifier(value)),
	applyParsed: (accumulator, value) => {
		accumulator.subjectKeyIdentifier = value;
	},
});

export const AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION: ExtensionDefinition<
	string | undefined,
	string | Uint8Array
> = defineExtensionDefinition<string | undefined, string | Uint8Array>({
	oid: OIDS.authorityKeyIdentifier,
	contexts: ['certificate'],
	defaultCritical: false,
	autoGenerated: true,
	decode: (valueDer) => parseAuthorityKeyIdentifier(valueDer),
	encode: (value) => sequence([implicitPrimitiveContext(0, normalizeKeyIdentifier(value))]),
	applyParsed: (accumulator, value) => {
		if (value !== undefined) {
			accumulator.authorityKeyIdentifier = value;
		}
	},
});

export type KnownExtensionDefinition =
	| typeof BASIC_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof KEY_USAGE_EXTENSION_DEFINITION
	| typeof EXTENDED_KEY_USAGE_EXTENSION_DEFINITION
	| typeof SUBJECT_ALT_NAME_EXTENSION_DEFINITION
	| typeof NAME_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof CERTIFICATE_POLICIES_EXTENSION_DEFINITION
	| typeof POLICY_MAPPINGS_EXTENSION_DEFINITION
	| typeof POLICY_CONSTRAINTS_EXTENSION_DEFINITION
	| typeof INHIBIT_ANY_POLICY_EXTENSION_DEFINITION
	| typeof AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION
	| typeof CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION
	| typeof SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION
	| typeof AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION;

export const CERT_CSR_EXTENSION_DEFINITIONS: readonly KnownExtensionDefinition[] = [
	BASIC_CONSTRAINTS_EXTENSION_DEFINITION,
	KEY_USAGE_EXTENSION_DEFINITION,
	EXTENDED_KEY_USAGE_EXTENSION_DEFINITION,
	SUBJECT_ALT_NAME_EXTENSION_DEFINITION,
	NAME_CONSTRAINTS_EXTENSION_DEFINITION,
	CERTIFICATE_POLICIES_EXTENSION_DEFINITION,
	POLICY_MAPPINGS_EXTENSION_DEFINITION,
	POLICY_CONSTRAINTS_EXTENSION_DEFINITION,
	INHIBIT_ANY_POLICY_EXTENSION_DEFINITION,
	AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION,
	CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION,
	SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION,
	AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION,
];

const EXTENSION_DEFINITION_MAP = new Map<string, KnownExtensionDefinition>(
	CERT_CSR_EXTENSION_DEFINITIONS.map((definition) => [definition.oid, definition]),
);

const PARSED_EXTENSION_APPLIERS = new Map<
	string,
	(accumulator: MutableKnownParsedExtensionAccumulator, valueDer: Uint8Array) => void
>([
	[
		BASIC_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(BASIC_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		KEY_USAGE_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(KEY_USAGE_EXTENSION_DEFINITION),
	],
	[
		EXTENDED_KEY_USAGE_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(EXTENDED_KEY_USAGE_EXTENSION_DEFINITION),
	],
	[
		SUBJECT_ALT_NAME_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(SUBJECT_ALT_NAME_EXTENSION_DEFINITION),
	],
	[
		NAME_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(NAME_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		CERTIFICATE_POLICIES_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(CERTIFICATE_POLICIES_EXTENSION_DEFINITION),
	],
	[
		POLICY_MAPPINGS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(POLICY_MAPPINGS_EXTENSION_DEFINITION),
	],
	[
		POLICY_CONSTRAINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(POLICY_CONSTRAINTS_EXTENSION_DEFINITION),
	],
	[
		INHIBIT_ANY_POLICY_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(INHIBIT_ANY_POLICY_EXTENSION_DEFINITION),
	],
	[
		AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION),
	],
	[
		CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION),
	],
	[
		SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION),
	],
	[
		AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION.oid,
		createParsedExtensionApplicator(AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION),
	],
]);

export function listExtensionDefinitions(
	context?: ExtensionRegistryContext,
): readonly KnownExtensionDefinition[] {
	if (context === undefined) {
		return CERT_CSR_EXTENSION_DEFINITIONS;
	}
	return CERT_CSR_EXTENSION_DEFINITIONS.filter((definition) =>
		definition.contexts.includes(context),
	);
}

export function getExtensionDefinition(
	oid: typeof OIDS.basicConstraints,
): typeof BASIC_CONSTRAINTS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.keyUsage,
): typeof KEY_USAGE_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.extendedKeyUsage,
): typeof EXTENDED_KEY_USAGE_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.subjectAltName,
): typeof SUBJECT_ALT_NAME_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.nameConstraints,
): typeof NAME_CONSTRAINTS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.certificatePolicies,
): typeof CERTIFICATE_POLICIES_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.policyMappings,
): typeof POLICY_MAPPINGS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.policyConstraints,
): typeof POLICY_CONSTRAINTS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.inhibitAnyPolicy,
): typeof INHIBIT_ANY_POLICY_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.authorityInfoAccess,
): typeof AUTHORITY_INFO_ACCESS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.cRLDistributionPoints,
): typeof CRL_DISTRIBUTION_POINTS_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.subjectKeyIdentifier,
): typeof SUBJECT_KEY_IDENTIFIER_EXTENSION_DEFINITION;
export function getExtensionDefinition(
	oid: typeof OIDS.authorityKeyIdentifier,
): typeof AUTHORITY_KEY_IDENTIFIER_EXTENSION_DEFINITION;
export function getExtensionDefinition(oid: string): KnownExtensionDefinition | undefined;
export function getExtensionDefinition(oid: string): KnownExtensionDefinition | undefined {
	return EXTENSION_DEFINITION_MAP.get(oid);
}

export function decodeAndApplyKnownExtension(
	context: ExtensionRegistryContext,
	oid: string,
	accumulator: MutableKnownParsedExtensionAccumulator,
	valueDer: Uint8Array,
): boolean {
	const definition = getExtensionDefinition(oid);
	if (definition === undefined || !definition.contexts.includes(context)) {
		return false;
	}
	const applyParsed = PARSED_EXTENSION_APPLIERS.get(oid);
	if (applyParsed === undefined) {
		return false;
	}
	applyParsed(accumulator, valueDer);
	return true;
}

export function buildSubjectKeyIdentifierFromSubjectPublicKeyInfo(
	subjectPublicKeyInfo: Uint8Array,
): Uint8Array {
	return buildSubjectKeyIdentifier(subjectPublicKeyInfo);
}

function defineExtensionDefinition<TParsed, TInput = TParsed>(
	definition: ExtensionDefinition<TParsed, TInput>,
): ExtensionDefinition<TParsed, TInput> {
	return definition;
}

function createParsedExtensionApplicator<TParsed, TInput>(
	definition: ExtensionDefinition<TParsed, TInput>,
): (accumulator: MutableKnownParsedExtensionAccumulator, valueDer: Uint8Array) => void {
	return (accumulator, valueDer) => {
		definition.applyParsed(accumulator, definition.decode(valueDer));
	};
}

function normalizeKeyIdentifier(value: string | Uint8Array): Uint8Array {
	return typeof value === 'string' ? hexToBytes(value) : new Uint8Array(value);
}

function decodeSubjectKeyIdentifier(valueDer: Uint8Array): string {
	return toHex(readRootElement(valueDer, { maxDepth: DEFAULT_MAX_DER_DEPTH }).value);
}
