name: autofix.ci
on:
  push: { branches: ["master"] }
  pull_request:
  workflow_call:
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-ts
        with: { install-bun: "true" }
      - uses: kjanat/install-dprint@v1
      - uses: kjanat/install-shfmt@v1
      - run: bun install --global --trust sort-package-json@latest tombi@latest

      - run: dprint config update
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'

        # autofix-ci will fail if the .github directory is touched
      - run: dprint fmt --allow-no-files --diff --excludes ".github"

      - run: bun --bun site:api

      - uses: autofix-ci/action@v1
