name: autofix.ci
on: { push: { branches: ["master"] }, pull_request: null, workflow_call: null }
permissions: { contents: read }
jobs:
  autofix:
    if: ${{ github.actor != 'autofix-ci[bot]' && !contains(github.event.head_commit.message, '[autofix.ci]') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - { uses: actions/checkout@v7, with: { persist-credentials: false } }
      - { uses: ./.github/actions/setup-ts, with: { install-bun: "true" } }
      - uses: kjanat/install-dprint@v2
      - run: dprint config update -yr
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      - run: dprint fmt --allow-no-files --diff --excludes .github
      - run: bunx @biomejs/biome check --fix
      - uses: autofix-ci/action@v1
