name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read, pull-requests: write }
    steps:
      - uses: actions/checkout@v6
      - { uses: ./.github/actions/setup-ts, with: { install-bun: true } }
      - run: bun i
      - run: bun run build
      - run: bunx pkg-pr-new publish --packageManager="bun" --bun
